---
title: "Initial EDA "
author: "Willem Krantz"
output: html_notebook
---

This is an outline for your Initial EDA. You can follow this outline, or you can modify it as you see fit. Do what works best for your project. 

## Research Questions 

What cards do I want to cut from my cube?

What color combos are fastest which are slowest? 

How can I offset speed so that certain decks don't dominant the cube?

Here I will break down the cards I have selected for my cube and through analysis gain a deeper insight into what the mana curves for individual colors look like and thus what mana curves for multi-colored decks look like. In a draft setting you want to try and keep a healthy balance of cards and curves. If one color is more powerful than the rest then it is likely that the majority of drafters will try and find themselves in that color. By comparing my cube to a 540 card Vintage cube I will be able to greater understand curves and what cards should be cut of kept based off of card type and mana cost. 



## Data Processing 

#### Data Intake 

```{r}
library(readr)   
#import data 

MyCube<-read_csv("TheCube.csv")
```


#### Data Wrangling 

Include R code and written explanation for wangling your data (you can make multiple wrangled data sets). 




## Data Visualization

#### Plot 1

Include R code to make one data visualization (I would encourage you to use 3 or more variables). Include a brief written description of what your graph shows. Is this graph helpful in answering your research question? If it is helpful, will you need to add/modify anything in this graph in the final report? 

#### Plot 2

Include R code to make one data visualization (I would encourage you to use 3 or more variables). Include a brief written description of what your graph shows. Is this graph helpful in answering your research question? If it is helpful, will you need to add/modify anything in this graph in the final report? 


## Conclusion

Include your initial intuition as to what the answer to your research question is using the data sets and visualizations you created. 